apiVersion: ENC[AES256_GCM,data:oTM=,iv:lLIPTR1OB12O1RK1krv3gdUPma4TzaPXTAdIY5pNz9w=,tag:AYdUyCsIGsKHnp9l9/WKhQ==,type:str]
kind: ENC[AES256_GCM,data:rYeOA7K+,iv:Uwj0dMZMrKJIos6HDbun56EA5jE8X/SDCKjbk0K5NZ8=,tag:46MMWerZ/5rzW4dcJgMoRQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TQH6YF54FpBJnSXw2xtwlWYc85G+PuQFX1Ld,iv:8Gzwlbe0mSVIOqYopBKIcm20thpZmmXdU3msIfSzq2M=,tag:9vvcEd4QX92YEgfu1Ghj+A==,type:str]
    namespace: ENC[AES256_GCM,data:hieTHInE,iv:WcO6DtBihf0lBDmEtSbSOdwAoTevfdSgkjaeYuhq0F0=,tag:xmBC0C95JhaDJ7gcaJ88hg==,type:str]
type: ENC[AES256_GCM,data:f1DWh5ub,iv:R3ZfMc0QxHIAghLDTRmQgN0U7CZYn2/Z4ALNqhtIOic=,tag:K6gw+mwdWd0C1sPmrMb+vA==,type:str]
stringData:
    runner-registration-token: ENC[AES256_GCM,data:LofBBQKxZLBWAu/J6qBMwzgxRvHhGpJfM2R5NijLyq34pbf/5rBZ9nqTG1/YlCBxt+qwDgXh+D7/LOn/orIXlg==,iv:1G99cC6B/3wBWkC+FYmz175CuTkM9ogMD0MdZziMKYc=,tag:LLpFi1ypBxSYtSNgwdd3pA==,type:str]
    runner-token: null
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQmVHaEh1c3NYa25WZDdZ
            SmwvZE1teVI3MjVzQ1ZtRnJjdWIzRmd4K0c4CmhHY0dLeUxrZGxhV3FTNTZpaG14
            WXdoV2hQWkxDWjRsU0hLcHhiZnF3cWsKLS0tIHJqRFZXamgxZm5xNW91MjZZakFu
            VXhBSjZjU0FsRUo2cTRnKzcvYS9DaHcKpgsrO6IFbHZlWnZ2RA/yanOGBsIHktPH
            3aRRQMdQh/clchq2SMG2hdgH/hL/ZoUrsaC1xdY7FoYiQkqVCgtEbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:7j0e3xnk+3zEeaq1J3D0vo2Hp9Dw2yGCJ3A13GqTV4Yapw7fKrdsi6Cy0JsDh5MDvYwUjdWzNtGCGEvsaF9wZLtBDGFlPwI30HbmfXa2w0j3O7NvA2i6njEye1+JuhGVstR+Y4v5dgRa9Ql5vz7eUICETch1wkSfWJggmfs5MkA=,iv:gcdBbBDhx7YFeHIaz0Wri75ccGJWQmYKvWJfK7wNyIs=,tag:ryHDFfRanuhTGHOdqIw2Dw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
