apiVersion: ENC[AES256_GCM,data:nXg=,iv:DdiEm7viWHMbJtMUsx7PC7ydEehMp1bbQePmJ0MKSRs=,tag:osAJKjFVQtZTV7qNrHPT3g==,type:str]
kind: ENC[AES256_GCM,data:qJVmYDD8,iv:3wVn7US9kVx0ieAfKn5+zYSFh9lJFNEAYIXEwq5tuuk=,tag:UJ0zr7cFqOHtxsLy7aXQww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kPcMGTY/zuVImuBmBbaUXMKawI0EqDAnzjA=,iv:DFRVIsgPZzYVibiKXzknr9XCadFP8317Ukqq6s0ZMmE=,tag:ZHZyXyFoS1QeRXOHn0QUPQ==,type:str]
    namespace: ENC[AES256_GCM,data:xqFwoip5,iv:tooEXTJ7xUHz6gdwE7sX9iXCznNk9SYzYJAzTJrqJX8=,tag:t0jUmF81r8OT81V9WN2how==,type:str]
type: ENC[AES256_GCM,data:R3R1VlVg,iv:t3iDkgMa9Vfu+x1qxhn87Trof2PHPkmwdQQlvi0IuXo=,tag:RGd5yEJAXvKEX+tYlQ0ESw==,type:str]
stringData:
    secret: ENC[AES256_GCM,data:6oYVYgj5/iU480WF85OY/UjpjkfEKAA20cuHS2oeF9bHTd7Gx8hAPjaeX7CfI+D0Obicq6RNw7gGvH9rpza0tq+bz1LR6Cqrv0W/IwYbz6J5p+wMLPOjcNKCFpMhNMOn//wZiZZIWRmMWCm/zZCTFa0RroEje1Vln22GYSgdPdsdc5finurlp85QYWVvzrPVnjtBcMuv125Rnz0ExJkdMVMM0a+w3DJNkeH9fQ==,iv:Lbigy75BQBwM9eHROuno/4rmmw2KDyFXwfu2UArp42I=,tag:GljZxOUrWk3nJRdsO6JTog==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERm95b20vNWJWWEtGQ1RW
            WWg2WEhkR1ZiUnowZzB2d1AyNm5tWXNQQlV3CkNrOUx4S3lpdVlzMkRyb05zSVFI
            VWNGTjhyNVBZYTBqaTZuSkplbFVWSzAKLS0tIDVXYVVnUEsrRkNnemxkaThwYTlS
            R2tQb2hDbmszbE9NZGExdkZVdVNVL0EK9P95DiWx3YwyQutTKx2v8i6DUs6WAvOQ
            DVXZ6FUubWbDoOtCQvjxA+XHUmhplR8s8BHPXhFunOjBzRkVgAyD8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:eJfbI48/6lknhxCKreResiHYbKBUZzthO1xBP3rGbEVpX00xAhPcGQAVhxTO+q8HGy2fVEhSrrZc+IajZ8nnU+p2Qy9uVifNOPLCYroMzZ3fJP1EL0awLzDhUJ7L2j13hP7xzpUBoD3pzsIPLI2pnjCq1hZxKNpmCvx9jTBVcOs=,iv:+r9QAGWp8v+3lzFGGZBwCYjTKA8TeoyPJEPXgzDJVQk=,tag:sTqgKJwYBVc3+DlPKUFeRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
