apiVersion: ENC[AES256_GCM,data:S08=,iv:uo2Wz0KZK6s0MiMYMTZpwODoC8Zrt3mRrP+pInyfysw=,tag:9p/2S30MAa6r5HRP3jIkXQ==,type:str]
kind: ENC[AES256_GCM,data:mwjpL9Vb,iv:j1/2MxQQzoJIqMahiHy5CUtEplOQUE3m4ws3Tvduxdk=,tag:V/b6Ffw+snIK94ObGO4Hag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:z7FqqZHQMsfioGUBi9HaCewb/b+OR0ImWTUO7w==,iv:GygvtT8/nQQc/pe8mJKKY38Wgvs2Bu/+x23duekCLmA=,tag:vIe8CgLkFeQQrbBWTOMSrw==,type:str]
    namespace: ENC[AES256_GCM,data:X3lD5oit,iv:PYLZh4zzLi3Z6GvSggfbvFLlzN5Xhn3FzLd1Ibrc3X4=,tag:0MI7GCjQw3lpRbE7ebjMWA==,type:str]
type: ENC[AES256_GCM,data:WbHCLFaJ,iv:Pg7OzzDK0SD9XlktblcqyUd0Sju0hV6JzRvjJlOCIcU=,tag:kE6P+4CZ0cMH8Rrbx7xe6w==,type:str]
stringData:
    secret: ENC[AES256_GCM,data:IMnzIG/8kmHjkHuVlo5uOP740C3Z9Kk/xXFIe+MK6RkCnxbo,iv:PXErYu9Qqp43tc37TdhCJAbI1IuEvsoUzllZczXTme0=,tag:zgwY8k8FbAvykOl2eA4lXg==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQk5uODFiTVFCUjRuYTBi
            ZHRwNEJCREJGdk5NUUtiRmZTb1ZKeEkwUHlNCjJreDdWYko3U2hJOElEVTdtQ2NX
            SzVOSlVjUjUxWXNMUFhKaTV3VW1SSVUKLS0tIHFCaWhJcnBMN3h5VmNnZzhGSmdS
            c0c5Vzd1RFRiSTVIa3dodjlqem1rYk0K0Zg7AnY+fEA0N9KaYhUxQrA6JdQcfjWu
            5pc4t/KNfQS1Ppnm9+V61Ei2NMNw9J1pk4RzDSaqDxqLCeG+AzKP2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:Vfuw1UyGTBqtOzHbPDda9HZMk7bemE0i78OUSgwFf1vTkcMZqKUHjTKLWx4d//QxP0ojeyEe8LDJkSpx7NS3eJYSH7i15AMtBlN/cIj7QnZS/xznUTd4DKhhrCEBmRa4uxr8U6wpxvYZppxa/JPOZ+nxEGuxrMcot2Gv/6tmmec=,iv:WYy8MSFMws/dxL9IbF4NnfJwJexc7jhRoC9LYorVhyE=,tag:COzVuYdeE64TKNTtU8FkHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
