apiVersion: ENC[AES256_GCM,data:c8c=,iv:7T2pSeOVDuHMPTQitN52tHwwhqq+apnHS/+aLJvTZWk=,tag:5zPwtyiWjmp6/Hdv24L12Q==,type:str]
kind: ENC[AES256_GCM,data:LybM1QUy,iv:yIuIdapNv9igxRgz/KS07xZlv3fBklM7QfIAWtgPRX0=,tag:D8rK4+HqhsOiRI4b1CPJdw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qCxPIp10iEHznIwdgtA4,iv:ZNBBU7OHaj4UEdgJZ9K7oHs1GJAVmi4vLE7NiALXIy8=,tag:hRc61uD1T/uKw+6DjQlQUw==,type:str]
    namespace: ENC[AES256_GCM,data:ck8RY2XK,iv:bKjSXxCLftSA/ha+0+SNuGKswzRzRK8M49LbR8zJcXo=,tag:DrICNm0yTZKETQefRr2aYw==,type:str]
type: ENC[AES256_GCM,data:BL+O3Pk9,iv:7qqqzn4vVLBDe6u70k4HpTpgtkuzLs7hCjAo8grgzv8=,tag:QnwZV9vsl2Pk4BQD9+hTCA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:Hbuj517V/qg4Xtc4oImv,iv:Wsma7Eok8YTjZJ8H701EkN8WVxGPCg9tw+E9qENzg0M=,tag:BElrQF1T+8TH7jxNgvnccg==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNk9ERWpNU2dIcHd4Wjc0
            bDFkclRPYkpLekpTMytBdnlpZXZGYktzTVZJCjRiMGdYU3FGRmVLQnFURm53ODVJ
            VXcvb1UvUXhFZ0VXbUQ5NzhIWjB5c2sKLS0tIGZzK1dHcGdLQVAzSkRSbXNQZlFa
            dFlHMHFVdTZtZEtTeStmS1hLU205QWcKrFyZylDeowDAF9s1Z2CXittaP471rQt/
            28PoK3FvEt427QAy79vSajLY4czJ6Qgn1aL94STwQ46hbB0uyCbnLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:6a0CNvTPfbFDH2dkIPs4Ih0AHNGMODbUv8zHnYxnC8XRIPGoxsA0wbgRf3tjPkh3yebKJUyUvyq2tWDLJIoEWgS4JqkxMCcsaD1cvu73dBxGXtkmfZ/kKWsq5r7IERNmramUbsSTnV9NSh9pplJ6c7uEbSS0LdgDhHunkETRNr4=,iv:Y/s1npXfWcfdRHBCQRhXnt6zPl9jjReCFIN4Z+1eEcQ=,tag:c7MrQE9b5MWeLpWRuoB1YQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
