apiVersion: ENC[AES256_GCM,data:VjQ=,iv:oNkVl0oooJdsRQC39FhbgymNbh3K/31PljwSSIOpP18=,tag:KOf7lxWIdVwfYbATnxzAQA==,type:str]
kind: ENC[AES256_GCM,data:qmX6dmFX,iv:Fcb1JaYV7RtK/sDxmaNB/MHeK8Bq0EdOA4obe3TpPZo=,tag:SVFqxPemhAFiR5TtacShvg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sNBuiyBI6JZ6rnZkJcsGVqWRSOGFssWpfXE=,iv:E08CZyBB6NSMnAGLjsAUYQZUbClP92cUhunh9jBXpF8=,tag:jzqDxL+DqMBBcb2q4o2vZQ==,type:str]
    namespace: ENC[AES256_GCM,data:YWMt3JVO,iv:rcYZKjC5EGIcZcqHIwpbTxVcSSoopYvCtxE39bh4MaI=,tag:A065pywbf9l4T7BuXWc/KA==,type:str]
type: ENC[AES256_GCM,data:gsXUHrub,iv:2Pwfj43wffVCfB7E9V54aDQi8kJdjGG83d6jhdRQVxA=,tag:WBRXFmYUIUnCAGCiFYdWgA==,type:str]
stringData:
    secret: ENC[AES256_GCM,data:xwjbtydRDX7KhlxvRdIgBFJTm7UW4BroqhTwZZmqGp0PcpCvASBJ7vasZk/kCvZSFz7WZWnwJPm/tyPkR6rsZA==,iv:GFtUJx7wb/SzQ2linHE1b2ZZY0MQSzFgGsXqZ3jILHY=,tag:BNVngQWFJI0BA8jZwqYp5w==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZllXZVZaendTbGZZTTFK
            cHdvbGRZNUZrdEtZd0hyVFB3NjZQd0FYV0FjCkVyc1NPM1JVc3dhQnFXK0N5Vktv
            Yzh5cmRqdnE3WUdwci9ZVXlnVlBrVGcKLS0tIE4vbWFvMUFRMWZ5Y3lwQWtWdEdU
            aFgxSVhzbXp1SzUwdnRYN1VkR1JGQTQKXC0lELg2NithsPMRzVMOrAY1+BNKuh4w
            rf/p89v0hFcml7C+7zKo9exjwfOuoH1dl4rlq0BNQM7ODkwGhi4LRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:dEXyKWj5mAZtqu/877udmD+DhEqRkM6V2xXksk2d7mpsPAPAIwKLASigjLy/nPIiTGdfs5FjSatEVRAxU0dm+Hk+EusTnG7vm4vuGAXGIkLdZCtvRM3ZfbEYlMr4KQ7KhBnsngIRSEwBKKFh6TLw4Fw3P7VDnA1516tewx9LdG4=,iv:C6SPmpoKHLMsCYcFrX7k9WrIgyYBwceSQzOLf68Ldms=,tag:reIV3fINc1ONdmqKkWkIIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
