apiVersion: ENC[AES256_GCM,data:8U8=,iv:fKfu69OxCmmerX/QiKc0utDc5PMuiNu9xOd0/x7ULj4=,tag:GuVG5f/hwXXLBWOoIgwPBw==,type:str]
kind: ENC[AES256_GCM,data:fTwjMchC,iv:yRYefXXCsECQCbtoHbANcT64B4LWekLvXJFFu/xMkRk=,tag:9JZn8XF9FOadJcJXr9NgBw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CkPQavNYmL9fKKHO,iv:2L/AovhgxoJIszP4bHA/aMxC3GfJ0vwFa/vNgs5STgs=,tag:myga/Z4RnuZ1ubRGBNQtzg==,type:str]
    namespace: ENC[AES256_GCM,data:CkU3vvvN,iv:ApEnKmpJM4ozOWE4etovWEbCS3NKhZmC6BAkkLxqCbA=,tag:uHSpRdUDLvIMxNaYT6Iz1A==,type:str]
type: ENC[AES256_GCM,data:r1KlQYZY,iv:lZaU7JxiV7z+PVvFaWLQjGJKfqTM5ZtuleMoL3s+Lu4=,tag:2IvDjezFUqWnMQfRPS6/tg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:NXBAMU/+ggfpmHjGMxLk,iv:dAN09v0wjfsdj1PHGfINxslhmDOASvxfdUFgHkoqsfg=,tag:jXzEvO9EeaI08WNlsiGzXw==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RHM5enNiYUtESDBBeTMy
            bGlKbXEwa0RUaGZ0TUxhaURQRmlqRGRWMUhRCllnS0pYZEJIWDBheFBQSXRNSDRI
            WnhEQXFRTVY1bGlMdjJkZjVobFZHNm8KLS0tIFArK1dSRnlCRGtrMjBKdjltdDA0
            cERqOHgweVFsaEsyTmREOENhMGR0RG8KON/9+mwWEq89b30D577uraTFzsO6yhQ2
            O4PB+5fsyT06HYQmK8DLVTCLIxhR4TgSTyQ5QVDzS8WYrd2cFhGieA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:IKwdELOmyOdARIEodQ5zjoXmf7SiFinDCz/01/+qhOJT4ZMc3r2yRyL5RjukUFEQZruMsAmmP9yrDN/XFQFiaMc/x6M49159nY/xZO0XC40Ky4Wrns4s9UG+IfiR4yy3yr1u9C6f3qj45Kp6eojF/gFghPB8AYfao1vbI/p6RUM=,iv:TKP6E3vW7a0u1ADpOAR8L993fqNqQjTf1Z0RT2zCp3Q=,tag:QNtotZ2fY8SMuH3PFkl6EQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
