apiVersion: ENC[AES256_GCM,data:S2g=,iv:O918vGuWydGtPCnMwvmaOMBr4DEJvFpP2bSnDaT44p4=,tag:gDXMaGJQk4Ovzpu4a9hKrg==,type:str]
kind: ENC[AES256_GCM,data:XupPiAlX,iv:LgowbBEknJnoowlvTiqYuMkVar1t8RU+tWlxg1bWCEc=,tag:HW6H7E6obNC/sYmhC18eug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iKsgs8k4wXDsH1ZfA/13mZmW09le,iv:jQee7NzPfo4SsMSUVpRnOLk9zWi5lUbw7X6k7+XQJy8=,tag:WN9Ll+iF1xhtJPfLDxJcsA==,type:str]
    namespace: ENC[AES256_GCM,data:SB1paiWE,iv:qbPvqfpnXAIW1tzQpEIJUjHqUj0eaDQ/AK9s4Qie5zg=,tag:4WSDQHKVMcU/9ALwcjLyCw==,type:str]
type: ENC[AES256_GCM,data:fUu8peVo,iv:l9qTMWv7QLg5UpXL3B4O4cjE86UGU1PkCdEj2KG9OnY=,tag:e/x4eMY15MNkHilsvYaZNw==,type:str]
stringData:
    connection: ENC[AES256_GCM,data:Kmimv6jjHgpqNIEIppC41Cn4Qz2cip/r5NYJKK7qaMP7N2KPw3hwu9LCXo09ZPKEaxIbLRAmSgGaASEH36o/PlBLX5J3DGjt/euDMBw7mDeXMWf+KOdgKnkq246TM+eIb7PLCEdn5AN0ERjiweMX3AIsjq/Tm0qOBH3PGeEXNjETD5WA/IiIi21eWgkuebftWL2MK35oIuYaZCYBinjrmGHihzvLPQ6exal0S0ovHE9zWwCLxE66Pdbdnd2MqtnXOIpP/QI0pDYeNhuBcQTbH/sSvXFadNrmSZo8kaTRlgmYiqH2zt0AYWrHShE=,iv:fNBno8y5q3FcmXgkTtQq7t0T9MNgM/gKRV8AB6xTl8U=,tag:JlfPJDcQSR7aKKV2g6dLaA==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXODN6cVZJRVlycWplV3Ix
            ZFR3R0I1azBuQXVQZ3k2TUdnV3FnSzRtalhvCm02dmlxQko5ZHg3Qm5GUGplRVpG
            RGxDVE5yV0JHWHhidExFeEZ3eng5WUUKLS0tIDZLcjQvZkJpamlRNHN1MUtEbXBP
            OFY1WDRLSTJ6S1ZTNnV4OHZJcEpxaWsKzgLlKsT18FDW8prVT6R7Z1IJQocr2ZPr
            KAjkNgKeLt5VciPemXgH0Zk9FrBFWAOGFQns+Io/gwkQG5zURRfNUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:fQeBjj9j6vUC2PTgE8jXfMNf+f6KgwORGsifRZIGvwUbb08SZWnEHXz6iycX4hbrICBZoetMuiCa2jYAaLy5O2UE3u/sXjIriMDTHIGM8KrZjDX6YxCY+5+8AnHHnasy/KVwJ23FXYMAPW8v7eOCK9wZ0V/PPv/LAYA+57xLVfc=,iv:MNpVpB3ROmB+rocABXxMl+dXH0bI1un8A1VvlQRzyZ0=,tag:WZD//PyLorMBtP3+bSj42w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
