apiVersion: ENC[AES256_GCM,data:6sU=,iv:de99TRVT+13BCwJ4k9WiVduGAWXMcfGD2owHm+rz98Y=,tag:rlCdFbKH70w1G4QMW9vuxg==,type:str]
kind: ENC[AES256_GCM,data:U5mIfNMd,iv:IeuZuZWjBCPDubq/Yym2/NzKBKwrfo6EdHtcrVz5BzE=,tag:KEOmuW0FkCvvOeHzWVmeOg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:i51X9WSN+M5/75pizg==,iv:95RBGm6UAx4CkwMv/AR38quzfwXRDO1iePwqq4rhHpI=,tag:btlH9MBsHQUSziJMrfMG0g==,type:str]
    namespace: ENC[AES256_GCM,data:QnNsPAkX,iv:WDez24v/Mf8M5yPNPMTg/X4bS+LHnJj0WYC2QRe3+k0=,tag:chTOoYEHyHMHUz8rp0MLTw==,type:str]
type: ENC[AES256_GCM,data:Ag8pOF2V,iv:aSc2oziv9iFRLZacS6nlftAHaqvjDnk84gOmSsTNFTE=,tag:3lkifR8Of3Pg8aIzLZeksQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:YmJdLev8Q3+aSYHsKna1IdeMtVP+HYCRZNTcCrDXBMQy5hOV8fGbrPIzFGeoHPQfX1TLnobsdgm6flL3w7VcIA==,iv:1dpF/pezhx5boPVKIn8tgqEyF5eVwhTCYP43pXDlVDU=,tag:oaKW/0FqXpDIlWsHvrjLbQ==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSUdGOWtUeHNnbDhZZ215
            SlNyMzZDQjd3WHh5ejZjTUhIcDY3eDlNWERFCnZpeXpic3FOT1p3Qkd4ZnZaSStX
            bTJDNlI3UHJHWENyQVU0dFVIblpDb00KLS0tIGxsM0ZpdmQ5cWUweUJUKzhZUExt
            U0JNVVZ1b0ltMFN1YzZBd1RLelJvdG8KNHmmMeBTqX+/Icq7uHsTzI33Xs3mnDgD
            lzZS/AhXTiDpjtBS021AjGcqfjNfWa3qZcER/+Wz2Vn26ZsFSQvk/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:id/HItExmI9zJURBWZjZ5cHafLqm2mit9C3vLyMKtzq1xa4SFLxGKBJ8WwWr8oUy2Zl5eP4otPlRXTiMS67bZiQOsUi5IX4lthyLXK4qtxwLZqaNiU0tWnA0gwdrITTXwi9Ly2+1uhQ8eJEYZir9quwAPgLAFhRpUWgmn0cb1fc=,iv:fdxAno+8Trc+E0+AjNhhD+t4XJnPlyGYuooxvDQ2Ups=,tag:D4fcBWe5JAojejVqlC959A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
