apiVersion: ENC[AES256_GCM,data:B50=,iv:7+x0pO7riy4c64fkdnu9ywA9REDMnqXGKPAeXHhJrMk=,tag:FCXbekLA8nTMk74xLulYXw==,type:str]
kind: ENC[AES256_GCM,data:Oxr3sh67,iv:L8trPposEwE+VKxfqbW7LoMKxVJdvQr7hTOoRR6dxKw=,tag:2xwBwlmh9JhRZ8YuNO/9zg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QCleIacaGn8sokw21BbXYmEDNCxnzJgXkuPEan1m,iv:CCKWIQ1OjzgLJWSq1WnOQKKAGDq84thToDIpOTKh0mM=,tag:Q36mtpLpS35+iu7S39eb9w==,type:str]
    namespace: ENC[AES256_GCM,data:fq4vsynv,iv:IGFOJ/ZS81Yz1grFmXcEw67Pg4bVzaEvhM3vZB0NYu4=,tag:hwUFHLpo1dJRql0QH6O+HA==,type:str]
type: ENC[AES256_GCM,data:cyiSoEkG,iv:R2yGBahnfga3tYg+8SvgS/XGcEJZp/M7/5/fVblaz08=,tag:abM2g8Mt17W/5qa2LZWA0g==,type:str]
stringData:
    shared_secret: ENC[AES256_GCM,data:C4yU/304ETSxPX6ezlTr+NvPZUGfc6Np2ynJHWcyAOduXDBvh9rode65/xo=,iv:mtLlcO35TSmDXDTt7uRDacNAND291VE5g+W95oPZUjw=,tag:eT2N8UyYnr42LeZLAuFZcQ==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcm9zbWNqZHBOdUV5dHpl
            eks0OEFRVWVwd1dVbzFNbGVTMndiTVJwNFJvCndlWHAzMVlOVnBRSTAwcGxKQlQy
            YmVRcDJ3UmovaTk2c0JiSnVpakJUOGsKLS0tIFk4QTgrTEV2R3MwQW14dEYyZkpJ
            eHNiUk02cGs3R1BzWVF5dDc3Y1E3ZFkKC9qMyJ8GdKe3LhWo535RC/f3qFlKcbOC
            WtHkM1FRhHtB0iVS4vatQMiYonNinfw3c0Q4ps+IQqguvtabe0ds6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:XV8BD/JjZYahKCPTelh+e0uSlgWZcYNQiwPhdYBK+xFbkDYrdWYv7WNQYsTmAWAQ18URctRAeDQeCXJrqZQyGYfE4AMN/HBysjlzAXHkWkBnv6fU+jQdtgHRrTL7yphLRMecq2Us8sHbwGtlHDFeNodhHd0+QhbBVHT4KoofU5Y=,iv:HwbtFFJr+vByB+6DdYsYt+TeLpl+pJKTd0kHlKQf2/4=,tag:rQlxkco71ueDk4SzPw6ZUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
