apiVersion: ENC[AES256_GCM,data:POU=,iv:D7IrCQ4WPVMuL9yoHkdWQ3Tl24OvWdO0W9/JUFyJ0AY=,tag:N6gVg5H9hMeHAJS7to1P2Q==,type:str]
kind: ENC[AES256_GCM,data:HFL2aqGk,iv:YIlxpXx6qHkAPMJxdbPEvT5oo9jzWZ+9wj7npuIB5M0=,tag:VfAa+89boWtmSVIdUjwl+g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7/T99D9Bbr1blKnvqHTaolL1FB4V8qFEJg2mAKGCVQ2xYN8=,iv:gNDYCckza0k+lPDi0IVqY6QAbiQCSvANLUMS8OOQqVE=,tag:fUhGaY4l0wa0BdGoQ958qA==,type:str]
    namespace: ENC[AES256_GCM,data:1Lu6jXfI,iv:jekCdACNV8yqhXYUNQGC2Ru6jbj5Ur4OdhVyJ/QrOH4=,tag:uelbJ5u6THpy95fEG3tUJw==,type:str]
type: ENC[AES256_GCM,data:zPC3Phay,iv:LYKyulZNvb1UdzWiMQLuBxj93kt4pDtrMytr3Hr9Ork=,tag:BjRcY7DqNdxO2CXN5ITQHQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:e7/E9quVpLamQ2AahepjYXTnAwHhtuE41wA4AjtdiXVt6hDahdXVgfTCJIrlyXC6e2syse20E2pgY+OMzyJ9vg==,iv:d8GP++E7ECfMghccI+8puIVS08P0lt4I5hEg4FZk7rw=,tag:u3/ZOVqvUOduQQSN+2FBHA==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQ3U3YWIreTFZM3YrakIy
            QVZLUGdYZmc3Rnl3RWk2aTFSOERHVWRMQ0ZvCjFUblhhOGtwWFllYTZFV0JyYVpR
            bGRWeFhSb1lQelF6WmhIaDZtSExKOEkKLS0tIFFPYitIYW5IalV5MGtkWVhQSDJ3
            R0Y3ZlZWbjNic1B1a1pKTVJTWDRoYzAK1HcbjhX9Au0g/F2tQ7tRANZVZD2jnB8/
            2yv1XnTs/DAWZ0bVqzu4kcRYjQ6Eiiyh9JZeqCVcwFrbB7hPog0i9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:FgtykbT2OuPrLn+dYAQMamIqL4ZltLJAkEzMPdjtKAK/ea+4fQfcYkTlWC5WDwfoEYtFg+H79trT2qpIltU0AMOB1si8nZ5Avfqc30R0Z7UoWoU/cItG5jqJq7AvDBHOMzk3U7373SIpT0zMQ+QJ8pNlPHnyiln72Z1IBh+67X0=,iv:iqXhFe2FzSlxLUBSKsfOdqYyyP/TgUVIPWl60cyTPPg=,tag:5QUt1FJy7U2gFQIkSq4IcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
