ingress:
  enabled: true
  anontations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: jellyfin.local
      paths:
      - path: /
        pathType: ImplementationSpecific

persistence:
  media:
    size: 10Gi
