routes = [
  {
    name = "gitlab",
    hostname = "git",
    namespace = "gitlab",
    service = "gitlab-webservice-default",
    port = 8181,
    private = false
  },
  {
    kind = "TCP",
    name = "gitlab-ssh",
    namespace = "gitlab",
    entrypoint = "ssh",
    service = "gitlab-gitlab-shell",
    port = 22,
    private = false
  },
  {
    name = "home-assistant",
    namespace = "home",
    port = 8080,
    private = true
  },
  {
    name = "sonarr",
    namespace = "media",
    port = 8989,
    private = true
  },
  {
    name = "longhorn",
    hostname = "storage",
    namespace = "longhorn-system",
    service = "longhorn-frontend",
    port = 80,
    private = true
  },
  {
    name = "pihole",
    namespace = "pihole-system",
    service = "pihole-web",
    port = 80,
    private = true
  },
  {
    kind = "TCP",
    name = "minecraft-router",
    hostname = "minecraft",
    namespace = "minecraft",
    entrypoint = "minecraft",
    service = "minecraft-router-mc-router",
    port = 25565,
    private = false
  },
  {
    kind = "TCP",
    name = "minecraft-rcon",
    namespace = "minecraft",
    entrypoint = "rcon",
    service = "minecraft-main-rcon",
    port = 25575,
    private = true
  },
  {
    name = "prowlarr",
    namespace = "media",
    port = 9696,
    private = true
  },
  {
    name = "radarr",
    namespace = "media",
    port = 7878,
    private = true
  },
  {
    name = "qbittorrent",
    hostname = "qbit",
    namespace = "media",
    port = 8080,
    private = true
  },
  {
    name = "flaresolverr",
    hostname = "flare",
    namespace = "media",
    port = 8191,
    private = true
  },
  {
    name = "jellyfin",
    hostname = "media",
    namespace = "media",
    port = 8096,
    private = true
  },
  {
    name = "grafana",
    namespace = "monitoring",
    service = "prometheus-stack-grafana",
    port = 80,
    private = true
  },
  {
    name = "mesh",
    namespace = "networking",
    service = "headscale",
    port = 8080,
    private = false
  },
  {
    name = "vaultwarden",
    namespace = "security",
    hostname = "vault",
    service = "vaultwarden",
    port = 80,
    private = true
  }
]

[pihole]
url = "https://pihole.lucalise.ca"
password_file = "/run/secrets/pihole_password"
extra_hosts = [
  "192.168.27.12 mc-rocket.privatedns.org",
  "192.168.27.12 mc-rocket-creative.privatedns.org",
  "192.168.27.12 mc-rocket-creative.duckdns.org",
  "192.168.27.12 git.lucalise.ca",
  "192.168.27.2 rufus",
  "192.168.27.11 kube"
]

[router]
host = "192.168.15.1:22"
user = "luca"
key_path = "/home/luca/.ssh/id_ed25519"
lease_file = "/var/dhcpd/var/db/dhcpd.leases"
