apiVersion: ENC[AES256_GCM,data:IxI=,iv:/JfCkAmCHnbrQSmSgjI3PwpsSLsAokRP+BOCwZTewf8=,tag:Jdg7ZZpZxHkxFdGR0Pnagw==,type:str]
kind: ENC[AES256_GCM,data:f/AMLs7t,iv:9BnmFpprd3DSx+M6GORHQncH4eNeZ8Flp7hxjYN2Ztc=,tag:5wPQWnC6dFGC1zw9EVMirw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0H5dAwdxW9psDWiSd8XonQ==,iv:RN/pzgBDgtJp2kx0h89Mjlu8OG8WmZaPW8YauFEv0M8=,tag:8SyAzoI6EiP/rgjIudxrlg==,type:str]
    namespace: ENC[AES256_GCM,data:YstYBAY=,iv:lVaW+/1ZozWSg6RqaDl9Ul4kpHucJFjmRzwbCTgxkrA=,tag:zMgh6J+BzxaLCKIdvzQZ7g==,type:str]
type: ENC[AES256_GCM,data:zpn3AKT3,iv:GkstbrRLo5zITzCyx9xldwCupx+EPCmRAM8rNzCkieA=,tag:zKEkBVk0aKfViexn4+TNcw==,type:str]
stringData:
    wg0.conf: ENC[AES256_GCM,data:eWal7ZWs0kyjOzRyTBuGTJDbsHdeuLMjzortvYXNGhXarI/HKPi1pJgDrUYjqr74iE2w4a4g8AcwilLVLU2CWJHdoI1uy/oLtkidXYiFpYdNPP0SMQZsMPRX5VsA5nGVFqBxH9EwTFWo0yKF750Mm+yedVHkl0hioKpa1LtZhu7ojEbEllBe/X8WtWbsHDDBwKRd46fIQvXOHryeq5lA8ZyPSRYdGK8kpmAD6yMAiVQVtzHRanGe4mGL4wHHjUxdSrOakj2IGpUeLHt3z4CCl+wOL/5wGeLvgz+/cERHG7lNcU5L7dXOgoo87BnZsZUhRzfhGGjKkqBHolzJYEFMxRg3UsqUTIom3uaaqD0FQ3gp5rh1uEwwlot+iCgf+JLClvmNctzN1EoD,iv:q5Sr5mWAzuNxsMpZ+0VSioDkVebYHDD2nzJsNetTo50=,tag:h3ysP8BiUlTAG2FV8opTDQ==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraXV1bTlncHJWaHVtWk00
            b2l0dWJpKy9HVlhEQ3VLUkVXRS9tRWhTQlgwCmxucjRaZFQyamJadzIvTW9LVm1o
            VzNzb0t4aTQvWXErakduWW5adHhvTFUKLS0tIGtLekhBWkFpZHFjek80WUZtNXFB
            Z2R0RElmMkg5aloyTzhPMGNaNndtWXMKGfS+LaOTTBpQtnkYSKSl7EdiW/rhiad7
            lIY8T4+Ndp+ZMNV8nd0lwlTkW2Yk9JVYuIamg5H9/iwPqEqwxJgrWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:vdvOnLKZUf7iqbjTN1p+gdhwoh5alLuvvh2YPTEWGOWhb2sUt+6+whV00G9lPGF6+aGYQjwHG3gNBukQFyWbsSzB7lDY+eg0YTUpz9S0AkzSia+IoLYLzZuSbw4tPRdNNvJSJamuO1w9uyiMdc9a8TtuZr9HITiRkYgXHRet9tM=,iv:16gkmhttJQUn+geC1RqoArjxLXk1lhiYeS0XAr4TkTo=,tag:iKoujRINiFxaspb8f40uPg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
