repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: jellyfin
    url: https://jellyfin.github.io/jellyfin-helm

releases:
  # Load Balancer
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.15.3

  # Media Server
  # - name: jellyfin
  #   namespace: media
  #   chart: jellyfin/jellyfin
  #   version: 2.7.0
  #   values:
  #     - values/jellyfin.yaml
