repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: jellyfin
    url: https://jellyfin.github.io/jellyfin-helm

releases:
  - name: jellyfin
    namespace: media
    chart: jellyfin/jellyfin
    version: 2.7.0
    values:
      - values/jellyfin.yaml
