repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: jellyfin
    url: https://jellyfin.github.io/jellyfin-helm
  - name: minecraft-charts
    url: https://itzg.github.io/minecraft-server-charts

releases:
  # Load Balancer
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.15.3

  # Cert Manager
  - name: cert-manager
    chart: oci://quay.io/jetstack/charts/cert-manager
    namespace: cert-manager
    version: 1.19.2
    values:
      - crds:
          enabled: true

  # Media Server
  - name: jellyfin
    namespace: media
    chart: jellyfin/jellyfin
    version: 2.7.0
    values:
      - values/jellyfin.yaml

  # Minecraft
  - name: minecraft-main
    namespace: minecraft
    chart: minecraft-charts/minecraft
    version: 5.0.0
    values:
      - values/minecraft/main.yaml
