apiVersion: v1
kind: Pod
metadata:
  name: headscale-migrate
  namespace: networking
spec:
  restartPolicy: Never
  containers:
    - name: migrate
      image: nouchka/sqlite3
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: data
          mountPath: /var/lib/headscale
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: headscale-data
