apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./metallb/pool.yaml
  - ./traefik/config.yaml
  - ./traefik/private-networks.yaml
  - ./traefik/private-networks-tcp.yaml
  - ./traefik/chains.yaml
  - ./cert-manager/config.yaml
  - ./routes.yaml

  - ./media/sonarr.yaml
  - ./media/prowlarr.yaml
  - ./media/radarr.yaml
  - ./media/qbittorrent.yaml
  - ./media/flaresolverr.yaml
  - ./media/bazarr.yaml

  - ./networking/headscale/config.yaml
  - ./networking/headscale/headscale.yaml

  - ./security/vaultwarden.yaml
