apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./metallb/pool.yaml
  - ./traefik/config.yaml
  - ./cert-manager/config.yaml
  - ./routes/media.yaml
  - ./routes/minecraft.yaml
  - ./routes/gitea/ssh.yaml
  - ./routes/gitea/http.yaml
  - ./routes/longhorn.yaml
  - ./routes/home-assistant.yaml
