apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./metallb/pool.yaml
  - ./traefik/config.yaml
  - ./traefik/private-networks.yaml
  - ./traefik/chains.yaml
  - ./cert-manager/config.yaml
  - ./routes/minecraft.yaml
  - ./routes/gitea/ssh.yaml
  - ./routes/gitea/http.yaml
  - ./routes/longhorn.yaml
  - ./routes/home-assistant.yaml
  - ./routes/consul-media.yaml
  - ./routes/consul-vaultwarden.yaml
  - ./routes/pihole.yaml
