[config]

[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty"
output_path = "~/.config/ghostty/themes/Matugen"

# [templates.rofi]
# input_path = "~/.config/matugen/templates/rofi-colors.rasi"
# output_path = "~/.config/rofi/colors/colors.rasi"
