apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: git
data:
  config.yml: |
    runner:
      envs:
        DOCKER_HOST: tcp://host.docker.internal:2375
    container:
      docker_host: tcp://localhost:2375
      options: --add-host=host.docker.internal:host-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: forgejo-runner
  namespace: git
spec:
  serviceName: forgejo-runner
  replicas: 1
  selector:
    matchLabels:
      app: forgejo-runner
  template:
    metadata:
      labels:
        app: forgejo-runner
    spec:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch

      containers:
        - name: forgejo-runner
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            allowPrivilegeEscalation: false

          image: data.forgejo.org/forgejo/runner:12
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          command: ["/bin/sh", "-ec"]
          args:
            - |
              forgejo-runner daemon \
                --config /config/config.yml \
                --url https://git.lucalise.ca \
                --uuid a9855b8d-0862-46e4-b7f6-ea5294c6d506 \
                --label slim:docker://node:20-bookworm-slim \
                --token-url file:///config/token
          volumeMounts:
            - name: runner-config
              mountPath: /config
              readOnly: true
            - name: runner-data
              mountPath: /data

        - name: dind
          image: docker:28-dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          args: ["--host=tcp://0.0.0.0:2375", "--tls=false"]
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker

      volumes:
        - name: runner-config
          projected:
            sources:
              - secret:
                  name: forgejo-runner-token
                  items:
                    - key: token
                      path: token
              - configMap:
                  name: forgejo-runner-config
                  items:
                    - key: config.yml
                      path: config.yml

  volumeClaimTemplates:
    - metadata:
        name: runner-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: dind-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
