apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
  namespace: sync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  namespace: sync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: sync
  labels:
    app: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing

  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - name: syncthing
          image: linuxserver/syncthing:2.1.1
          ports:
            - containerPort: 8384
              name: http
            - containerPort: 22000
              name: sync-tcp
            - containerPort: 22000
              name: sync-udp
              protocol: UDP

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC

          livenessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 20
            periodSeconds: 10

          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: syncthing-data
        - name: config
          persistentVolumeClaim:
            claimName: syncthing-config
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: sync
spec:
  selector:
    app: syncthing
  ports:
    - port: 8384
      targetPort: http
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-sync
  namespace: sync
spec:
  type: LoadBalancer
  selector:
    app: syncthing
  ports:
    - port: 22000
      targetPort: sync-tcp
      name: tcp
    - port: 22000
      targetPort: sync-udp
      protocol: UDP
      name: udp
