apiVersion: ENC[AES256_GCM,data:Tvg=,iv:YtGmtlVfi+4IZMWhQWxp8ZdH4xelfRj3G30t5Sj+Ga8=,tag:SRSKdAPbke+lPcBdzaR3Wg==,type:str]
kind: ENC[AES256_GCM,data:AlylRFS0,iv:fRMa5gvYtRFoy50Xjs8bW9z9Hw8FDgVXD598T3y+GBE=,tag:t23cqKZApcpUDZWyBi9gFQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w2hJTfoF86KncdXiycPb4KjZcmnuqA==,iv:/kiWjPPIjuzoyUKmun+7WbAkcOk+b/LGEaq64FVEJNY=,tag:khrujSProYfdc0Tljp7IGw==,type:str]
    namespace: ENC[AES256_GCM,data:3Ei/6Lo8B19Y,iv:vRPbgJKIHNTjPG3PHVvvfLiTsSPlOFB4l3foLDgd9qc=,tag:BPWaCdN8PcjDhdMDSh/DoA==,type:str]
type: ENC[AES256_GCM,data:5ADmjP3C,iv:jbQO/KJgzEp+G+ooXqy4rNhm9ranpA1bVfmp27Gj4kg=,tag:rRVC2QNQ2cakTFEKPWSbXg==,type:str]
stringData:
    key: ENC[AES256_GCM,data:AVA/RKKB/MA28bahaU97L4wWYfeqQtLYy0Z+9V2wmV3epV0/kkySzt0VF8T6KEU/bGfHn/HB89TMFkCA,iv:5NbqU8P/4atbvaxpBlGSpvDoOqZ688BHEInrw74VZr8=,tag:0dGqw3xcuhHQG+hAyYOi5w==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbE5Mclh0c2xEcExkQU5i
            dzdnQ2xrMDNyYUJ1SEZmd0QyeCtzazJvbFZVCjFxNTNWZ1FVVHR4Y0JhbGZ6OHND
            NjcrMzNiN0ZUL1Y0M3V6cE1kQXdxNTQKLS0tIGFDWERhdjJwVFZLdndMR3RIZUZE
            VXZRclFkakNGZFdxSHN1NHVhOS9xYU0KjdSSpXJkKKa7yQdrWd2IPqvlajMplLWh
            HDThnThZ5kjqWZBwfFDAoHaeQCiLWCZPQuGsBLmdAPL9j07b58KrfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T04:52:04Z"
    mac: ENC[AES256_GCM,data:D5vWZtUo4oewZeb9l8u4Nu/Fns0ntEYjkNXq4nsdUoyP4TO6R3SsNztUUE8XP8xnIs4ujfclv79ck48BXqSPwv6vod8sGagtOdYCluSuBvfs4FUQzYaJ8VplYc6jAZa/vEt1MeTc0CuLXyiujJ3dEl62hsc/4dhr3VdL7/+Z7Bc=,iv:KqqWdG89JKmOWwUhLMLyzWSjU2bj7UywdsFOTcZF/NQ=,tag:9DnNFEyaFmQE6Jaq4tJFRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
