apiVersion: ENC[AES256_GCM,data:5M4=,iv:DlgagKjtUlAkB45pCBYHBnz4gOjZ82dVH738WxHjdeo=,tag:kCUc6XDy9qTwtdavSkpDhg==,type:str]
kind: ENC[AES256_GCM,data:LlYSJBSB,iv:txgZ6IHWBqf7GyGtAw8vHOG1MVRskjL6bEt2jMWYdt0=,tag:3kE/ahwza/BZ81k/oGP3VA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GALkblmP1poFe8bk0mNl7Q==,iv:uKo4QLjsUFFZm6qhzj2UcJQ13uSF7kbAV0d0Sbc3FWI=,tag:uAApeBc6TxReMNKS4yX96A==,type:str]
    namespace: ENC[AES256_GCM,data:xWtAph3hm5Bv,iv:g28rQ1eUmNYPxVjB+t3cLkzoNKfsXIokFfbXdmIX/vk=,tag:fgqwtLy0+xbIQ4WsHYIvxw==,type:str]
type: ENC[AES256_GCM,data:GMjzIeYy,iv:m5DasCAvURnjzDb4S7ygSSviPLdVGVYXs06RbbSg7xs=,tag:UgJIwURgJ38426uFmvrKxg==,type:str]
stringData:
    rcon-password: ENC[AES256_GCM,data:dQwstMaOwC4YsnWNUfoiMg==,iv:qxwEfLmCUKMwp4dfHTnkEJo4j8FGjIDAIYqKSYhheOw=,tag:uoqQyzdojl4OkpmscB4byQ==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQXJyamZtcXFjYUc1WkFF
            bmJCV2lJZi9IbGE5aWYrS085NnV1cVo2YXdvCkZVKyt2UTFEY2NyaDVVRy9DS3Br
            VjJySWZ4cktxdUc4TTl0bW1QR0p2OEUKLS0tIGlhbi9VNEc3QnhBV1grZm9PM2gz
            UEZGL1o0R0lkd0pzSUpwWlJ6Ym1LbXMKK9cqZHMMamA6MY0rKy1X0yVaYcivvMO4
            8MhYCs8HD/oSE2RaAMFIrRquEGBqxxCfAnbfB3dwxdLjnOsI3uWc/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:aaLHpaTRx0SkqBwjf6Voniyj7Jmn3lVSIJKiC7JmKkXxxkzvMWcYTj1rp7kx969Q5iDqQYOjk9dBg6dncp9OI4JUPsDn6PlbP/JR+ezRmq5BKvpl2I4CrVsaclnKZe5UvVIpNWIwCzsx80Pjx9MKvPTE6rloQidb5ZkA4sipSTk=,iv:D8PnIT3z0PGLuAH9qnv6mM4qSkip2+6/bmAogOOhGPI=,tag:Cb4Q6MzsC3MTQRTvDmIDUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
