apiVersion: ENC[AES256_GCM,data:d80=,iv:gmC9QnFOuH/sjRyK3dtvEQ+ZXMQbhYTiXcnpMfzNACc=,tag:dBGr67UGuE+rd+YaRmy2/Q==,type:str]
kind: ENC[AES256_GCM,data:cL2rxsem,iv:dkrviHhT7Ygg3858udkNvwUdsV28945PVBNafILK6r8=,tag:Lbr9hDHyxSHG9GaXai+Gfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pBAPgBKSO2JuTOBGc+h9hu2jWg==,iv:8AlXCi19pCLgwDrbYVEAp8dPVLl0RF/MOWykLg9kF2c=,tag:cAxD+Hzy+tdhRn3sQBVDUw==,type:str]
    namespace: ENC[AES256_GCM,data:I6GbMGI2+ow=,iv:qFXYY2RV9z9i9R9+L1qcOxUZysvsbgVDjv5RdfoJBDc=,tag:sUoBullHBKN9pDulVGL86A==,type:str]
type: ENC[AES256_GCM,data:SApxf6fx,iv:1cQ2pUO402WURyqlA188IK3O88NC4mwOGQm+d/vp4JM=,tag:3Jl10/NLc+hOEa1LxxpGgw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:bB/AfVPjHrZO9Tg6gJg=,iv:9KjxGKYak+oX0fDkDFAHNLKuzyQNX4Esi7gc86VQ9fc=,tag:gQn0+DIo0mAGoSJj2oBg1g==,type:str]
    postgres-password: ENC[AES256_GCM,data:shBQQC97IeAkbBY6z84=,iv:A0X5aFfqLSkINnEqakUaL/doKQNPdkt/l1Xl6bS2tW0=,tag:FekIejJOqVENvyOoZifv8w==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRFhmWVZqZGh2QkZiQkUz
            L25abWFTTHhJdG9abExKK3JQYUJmMVhZQnlFClpFN3RwQnZLcm1zVGNSQThFbm5v
            T2s5KzlqMnQwSHZSbnI3RkV3ZXh2VkEKLS0tIGp0RWZmWUc5WGNqNlIxOHhLWG9z
            dlhoVDAwWnVMTGI4UjhCNjhVY2owZnMKIGyjj+F8QFNCZVLTPw+OM1ToBjaDrTCT
            OdlojocPEN/kxyVsQnbegGKbjid7SesqexvlEB3iOZaf1nKj5HaAjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:1sbDvnhRYQ3GFqRK++02YGmZYkfmxyI1CzzHOeiXJv9gKECgzz/xsRdRPjZbBZBaIcgY+R9RV4o6cAtXTx1Q9gK4E1HKaXR90VosvtTEfPQQUqjy/yKgTTsfOUT7IyEBaZd/ovLxqZYuiWub+gHN9tal/UU6onySC+sDrCZGKj8=,iv:44Vs8BYHHgIYVkxJ3U2eGZl1sXdXhe0SbpyLNnSL1Jw=,tag:Ovmw8eAwyJQmlZohgxgwTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
