apiVersion: ENC[AES256_GCM,data:1gY=,iv:Kb9qfrqKztlNzMkOrmgoPMqoKxPP/+liFdut9tI0PUc=,tag:lSATxrqRm4KVQG4LdCyn2Q==,type:str]
kind: ENC[AES256_GCM,data:SfxB2VjJ,iv:XxNqggoPBS7ygOF3KVZ9udW+beuvqOOg0mtmLjlR3Pk=,tag:aAiI80I8z2ESi2qX2GkPkw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B99wSsxsWmFz/zIz4SDA,iv:R1T1/G2e0DxinPwN6ZvSZN31LU8cbapILrFmMxksVr4=,tag:KF60DpZDJEKyYsF5MSu/sg==,type:str]
    namespace: ENC[AES256_GCM,data:6FPYlDNUfFE=,iv:8NRNZSSwkfZBj9oFT9aslvTig1V3pQEvAJvD9JWpKS8=,tag:cb2oAPMeyjpPmoBJ8zlovQ==,type:str]
type: ENC[AES256_GCM,data:/AsBPyPs,iv:NwTaJBJKAkjvqYLQIW67iQjwVhhKYZFz8m3WgO6rNdI=,tag:cMAP8TL3XLHEsYf4q56wSw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:hurzLs41rdkxk2CGkO8=,iv:jlphlRNvJcRC8ypjTa9qKgLluvtfszdpeFUOdQ+/Uko=,tag:K8ulFFQcCscSvMFS272vBQ==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZkJIS3M2TG53Uzlvb3pw
            aUZvY3Y4Y0NtYWdWZWdLQmVnY3R3QU9sSFFFCnlFb0dreHZEU0RVWWVCK0NiUXFU
            SFBkVStjekZmS3FYSEZpUi9iU0lCT28KLS0tIEhaSURSanoyLzBEV1V0bVJQM1FB
            Q01FRFhJU3VCeFR2V0pOSmFsdTRTWFUKr8OuM1fW/j1FM2UH2CK1R6bCvx6Lm66t
            ZioQn+x9XZiHl+8dGXr1kMwQGS1uYm2cdTOvgDCIQXqHdRRFXsOJ7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:ftUVuCh4Y6BNvlvWU4kBbGEl65qHbsWioOJvLbbMZN+oTk8//au5bJNimfu7u3pUVdKjniwnVOjaP277NcFNADC0JGnQ7bKwafKgBDC0zHrXwb2zQet9ISvgZInGMAvZcY7alwnGh7/jJUZWjUcS75pm087bOJ7sspTs7LqVYCY=,iv:35HSorYvYjdw+Dj03/ZgqaOaqobeYS8ZCUOuZ8ZQV2A=,tag:prBqoyyH6nFfPxoaFi4anA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
