auth:
  existingSecret: valkey-password
  existingSecretPasswordKey: password

persistence:
  size: 2Gi

primary:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi


replica:
  replicaCount: 0
