apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: minecraft-main
  namespace: minecraft
spec:
  entryPoints:
    - minecraft-main
  routes:
    - match: HostSNI(`*`)
      services:
        - name: minecraft-main
          port: 25565
