apiVersion: ENC[AES256_GCM,data:rbw=,iv:DjiP8VNU+p5/akmTlbIemZSnCMK/yCEyUcLap5bSLhU=,tag:MKLJSMPIacqBOEOd+zqRqg==,type:str]
kind: ENC[AES256_GCM,data:ybsPvub2,iv:xGvYRnCB4G0X7gXMuqWqAAPL/4C8pKNSAEmKrgSKXx8=,tag:FnJfLLwh8HG3FaXbE49opQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2TbIcgyoZTEsjjBz7QRN3+GZ9g==,iv:Zr0HzUpvincjZJQ3qK5vhXwalcoCamp4c/jnQy23B8A=,tag:WFDeJnXIdBHHHTIOVlxQwQ==,type:str]
    namespace: ENC[AES256_GCM,data:cqFtR5ZSaIu3MuOf,iv:G6Gho+JLh+qtUUQXBXCVCXVvkSvEGObOpjuGF8N2Xms=,tag:PddygVa79YUeoNvVr2p+9A==,type:str]
type: ENC[AES256_GCM,data:mWKjKXOg,iv:r/xIeVp+4TqUWOf3vK2rdiJHXNFOsNqc1RHeChcKeB8=,tag:lqVg50X/AQ6IU+APW3p8mQ==,type:str]
stringData:
    secret-access-key: ENC[AES256_GCM,data:vi3njm6G+YR6nYkIOeYbUmX76pNxBtYeHvBLchCW5rNRqEntXOew2w==,iv:eQdfVr0f741I2rvsONJL3I9N6iXslMrvBRPbSvqfP34=,tag:7gsNAaUE85ZTMzbHb8foLA==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Tm5VNitmYU42djF0UHFO
            ZnovcjQ4cG8rYzllbDFMYXdnY0xVUzYyRkdVCjFYOFNicng3VFlscFpLSituQWhW
            TzNqU3RQUHJBbmVQTU54UitHRzkyWHMKLS0tIDJvUjllVCt2WHB5bWdySXh6VUJM
            NkpLMk92c0E5OUl4aVBOYjF2Ym1OS00K0T3kHPkERt8zlDN1TALALVf4vSIKrO21
            hGZWvdyJqmpUidc9kZrOjXl2avAUXk09ewxWyx3u0djFJ/YFrjwWiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:Dmzy1L5i75+G8wtSaFe3Se4mXb4CQJ7MAI/5qBcX/DCsfPORGDhnoUs6wVoeZWdfX72Hyit4qGMQ3IeRoXn2jTiz9CjKXEvNTmvV6BOaQpWr40CLPR8Axr9PkqGwD5f6ylb+LDNF2vKPUlg4e9YpmItFuNajjtpzyaphda0+LWw=,iv:d2RUcgcniBx6dsPW0xz0YPzCX8bJTsYx3PDtO2+l+qc=,tag:zo8Ky/tsDJxFd423iAJKVw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
