apiVersion: ENC[AES256_GCM,data:blo=,iv:q11fL6L/miQsj5TbGm8NsJac2O0UN94RUwSyBcG1Pg8=,tag:Imuh1iqjadudxL+KvOaQtw==,type:str]
kind: ENC[AES256_GCM,data:cQjbjYg+,iv:4hVDbP4O4sEAaBKOMbqOwFjqVJI5Qetr7agtjz2rS8s=,tag:avg6LIh5JAs22LWbbDSMiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:emxCs90U5PEdMWEGpJIR3BtP,iv:qECcxeEf671jlzwoxT/H6QWdRau2nCn9PyiqFiRHwkw=,tag:Y+W90V1SLzwk+WWKpwUzNQ==,type:str]
    namespace: ENC[AES256_GCM,data:p9bK,iv:JFjhpwvC3/XYfgll58R05nroOXgZCr5+Jei+h2gtUFQ=,tag:p2twEbPg7mINTmD2Q/idOQ==,type:str]
type: ENC[AES256_GCM,data:m75X5FTG,iv:04Ci2vUZyG/eVf0gJDz/zkRyLcoNOR4drlLGCyBK5q8=,tag:VFDhZdnmksGk/AcLVvXyyA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:AbFtp8f16LdZ5uwAs8TXmQ==,iv:ItTX8j3CN5k388euPq09ol+Yy0rkTxOz6MIjQ6qMim0=,tag:n6nz2yynKgUuN/a9mOxSWw==,type:str]
    username: ENC[AES256_GCM,data:vvAIdW/18zzVyEY=,iv:jcbGs4qcCOBhmWzVZ/em1YS6jC9OWId7vDv4ssRBtUk=,tag:og5cx1MMSzqMzqhIjIWi/w==,type:str]
sops:
    age:
        - recipient: age13rqgrxh0fm23n3krf6v7yrrlnhhvs8256cusxqfs2l5xz8rgavssdhte4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbHp0WjVpYTNUNk9ENjF5
            c2hIL1ZuT3dmaEhDaGp6Tm41WjZNUkltZkVZCmdUTnpGR0R5ZGhvMElvQ09kbGxE
            dnM4eWlKZ3pIS0Rjb0hadnJ2ZmFueEUKLS0tIDI3OWZsWXZqUjJ6VTl3c21hRHhh
            cXFBZDNJWUFKZjhwYjdRcmtpczlpZEUKwcAA7QZKh7e5o6loq2d3PHzknYHbU9tZ
            bGXftlVA3cuQATgZxQviOw3rYa9/IrcVxki3V3n7fNbvLVYWoivOqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:26:58Z"
    mac: ENC[AES256_GCM,data:K5kJLaLATYx6te5SoHnwYLNuZnr6ad0TYzVHNW5ko8KjK8pjE56Kw54GDTgM0QONCLeYeJxMg1vxL7wuGIXBY29jDaTKv3kJn3tQxn7RfB2GhzIM9bUa/aobudMmb3wV2YYsHnzRFcX6T+MQv9av00DSy4KjMDGGBlkF+T4vZ4E=,iv:FsoIq7GAgv33mab5NZjgHGVlJupfJpIMuxksfW29svE=,tag:cv6HRINEsKFrV7gGqLjh6Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
