persistentVolumeClaim:
  enabled: true

DNS1:
  1.1.1.1

serviceWeb:
  https:
    enabled: false

serviceDns:
  type: LoadBalancer
  mixedService: true
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.27.13"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
