resources:
  requests:
    cpu: 1
    memory: 500Mi
  limits:
    memory: 5Gi
    cpu: 2000m

minecraftServer:
  eula: "TRUE"
  type: "FABRIC"
  version: "1.21.11"
  difficulty: hard
  motd: "A Minecraft Server."
  gameMode: creative
  memory: 4G
  rcon:
    enabled: true
    withGeneratedPassword: false
    port: 25575
    existingSecret: rcon-credentials
    secretKey: rcon-password
  modrinth:
    projects:
      - fabric-api
      - tree-vein-miner
      - lithium
      - servux
      - ferrite-core
      - carpet
      - elytra-trims
      - fabric-language-kotlin
      - c2me-fabric
      - scalablelux


nodeSelector:
  kubernetes.io/hostname: kube

persistence:
  dataDir:
    enabled: true
    Size: 4Gi
