resources:
  requests:
    cpu: 1
    memory: 6Gi
  limits:
    memory: 7Gi
    cpu: 2000m

minecraftServer:
  eula: "TRUE"
  type: "FABRIC"
  version: "26.1"
  difficulty: hard
  motd: "A Minecraft Server."
  gameMode: creative
  memory: 6G
  rcon:
    enabled: true
    withGeneratedPassword: false
    port: 25575
    existingSecret: rcon-credentials
    secretKey: rcon-password
  modUrls:
    - https://github.com/gnembon/fabric-carpet/releases/download/v26.1/fabric-carpet-26.1+v260402.jar
    - https://modrinth.com/mod/elytra-trims/version/NLOF6eKu
    - https://modrinth.com/mod/c2me-fabric/version/0.3.7+alpha.0.61+26.1
  modrinth:
    projects:
      - fabric-api
      - tree-vein-miner
      - lithium
      - servux
      - ferrite-core
      - carpet-tis-addition
      - fabric-language-kotlin
      - scalablelux
      - axiom
      - pickup-notifications

persistence:
  dataDir:
    enabled: true
    Size: 8Gi
