resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 500m
    memory: 128Mi

minecraftRouter:
  mappings:
    - externalHostname: "mc-rocket.privatedns.org"
      host: "minecraft-main"
      port: 25565
    - externalHostname: "mc-rocket-creative.duckdns.org"
      host: "minecraft-creative"
      port: 25565
