resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 500m
    memory: 128Mi

minecraftRouter:
  mappings:
    - externalHostname: "mc-rocket.privatedns.org"
      host: "minecraft-main"
      port: 25565
    - externalHostname: "mc-rocket-creative.privatedns.org"
      host: "minecraft-creative"
      port: 25565
    - externalHostname: "mc-rocket-old.privatedns.org"
      host: "minecraft-old"
      port: 25565
    - externalHostname: "mc-rocket-rlcraft.privatedns.org"
      host: "minecraft-rlcraft"
      port: 25565
