apiVersion: batch/v1
kind: Job
metadata:
  name: minecraft-{{ world }}-backup
  namespace:  minecraft
  labels:
    app: minecraft-backup
    world: {{ world }}
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 0
  template:
    metadata:
      labels:
        job-name: minecraft-{{ world }}-backup
    spec:
      restartPolicy: Never
      containers:
        - name: backup
          image: busybox
          command:
            - "sh"
            - "-c"
            - |
              tar -czvf /backups/minecraft-{{ world }}-manual.tar.gz -C /data .
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: true
            - name: backups
              mountPath: /backups
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-{{ world }}-datadir
            readOnly: true
        - name: backups
          nfs:
            server: 192.168.27.2
            path: /backup/minecraft
