apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: private-networks 
  namespace: consul
spec:
  chain:
    middlewares:
      - name: private-networks
        namespace: kube-system
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: private-networks 
  namespace: home
spec:
  chain:
    middlewares:
      - name: private-networks
        namespace: kube-system
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: private-networks 
  namespace: longhorn-system
spec:
  chain:
    middlewares:
      - name: private-networks
        namespace: kube-system
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: private-networks 
  namespace: media
spec:
  chain:
    middlewares:
      - name: private-networks
        namespace: kube-system
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: private-networks 
  namespace: monitoring
spec:
  chain:
    middlewares:
      - name: private-networks
        namespace: kube-system
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: private-networks 
  namespace: pihole-system
spec:
  chain:
    middlewares:
      - name: private-networks
        namespace: kube-system
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: private-networks 
  namespace: security
spec:
  chain:
    middlewares:
      - name: private-networks
        namespace: kube-system