apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rfc1918-chain
  namespace: home
spec:
  chain:
    middlewares:
      - name: rfc1918-only
        namespace: kube-system
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rfc1918-chain
  namespace: longhorn-system
spec:
  chain:
    middlewares:
      - name: rfc1918-only
        namespace: kube-system
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rfc1918-chain
  namespace: media
spec:
  chain:
    middlewares:
      - name: rfc1918-only
        namespace: kube-system
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rfc1918-chain
  namespace: vaultwarden
spec:
  chain:
    middlewares:
      - name: rfc1918-only
        namespace: kube-system
